export enum Fonction {
    AJOUTER_MESSAGE = 'AJOUTER_MESSAGE',
    CONSULTER_MESSAGE = 'CONSULTER_MESSAGE',
    MODIFIER_MESSAGE = 'MODIFIER_MESSAGE',
    SUPPRIMER_MESSAGE = 'SUPPRIMER_MESSAGE',
    SUPPRIMER_UTILISATEUR = 'SUPPRIMER_UTILISATEUR',
}
